---

- block:

  - name: Install mariadb-server
    apt:
      name: mariadb-server
      state: present
      update_cache: yes

  - name: check if DB exists
    shell: mysql -e 'SHOW DATABASES;'
    register: dbstatus
    changed_when: false

  - name: create database
    shell: mysql -e 'CREATE DATABASE opennebula;'
    when: "'opennebula' not in dbstatus.stdout_lines"
  
  - name: check if user exists
    shell: mysql -e 'SELECT User FROM mysql.user;'
    register: userstatus
    changed_when: false

  - block:

    - name: create user
      shell: mysql -e 'GRANT ALL PRIVILEGES ON opennebula.* TO "oneadmin" IDENTIFIED BY "StrongPassword";'

    - name: flush privileges
      shell: mysql -e 'FLUSH PRIVILEGES;'

    when: "'oneadmin' not in userstatus.stdout_lines"

  become: true